spring:
  redis:
    host: localhost
    port: 6379
    database: 3
    connect-timeout: 1000
    password:
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: -1
        min-idle: 10
  datasource:
    url: jdbc:mysql://localhost:3306/Test
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true