
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/oauth/token
      client-id: admin
      client-secret: admin
      user-authorization-uri: http://localhost:8080/oauth/authorize
#      grant-type: password
#      scope: all
    resource:
      jwt:
        key-value: 123456
#      token-info-uri: http://localhost:8080/oauth/check_token
#      user-info-uri: http://localhost:8080/oauth/check_user
#      prefer-token-info: true
server:
  port: 8090
  servlet:
    context-path: /resource