security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/oauth/token
      client-id: c2
      client-secret: c2
      user-authorization-uri: http://localhost:8080/oauth/authorize
#      grant-type: client_credentials
#      scope: all
    resource:
      jwt:
        key-value: 123456
#      token-info-uri: http://localhost:8080/oauth/check_token
#      user-info-uri: http://localhost:8080/oauth/check_user
#      prefer-token-info: true
server:
  port: 8091
  servlet:
    context-path: /resource2